POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content":"CSS",
  "important": true
}

###
PUT http://localhost:3001/api/notes/60bf494ad34c64552078758a
Content-Type: application/json

{
  "content":"Welcome to web",
  "important": false
}

###
POST https://salty-anchorage-76602.herokuapp.com/api/notes/
Content-Type: application/json

{
  "content":"Let try POSTMAN",
  "important": true
}

###
POST https://salty-anchorage-76602.herokuapp.com/api/notes/
Content-Type: application/json

{
  "content":"Herolu is a good start",
  "important": true
}

###
DELETE  https://salty-anchorage-76602.herokuapp.com/api/notes/5

### 
DELETE http://localhost:3001/api/notes/60bf4b92bf7de55124ecd742

###

